// Per-state data loader. Loads JSON files generated by scripts/extract.mjs.
// Each section's data is in its own JSON file under /src/data/states/{abbr}/

import { useEffect, useState } from 'react';

const cache = new Map();

export function useStateData(abbr, file) {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!abbr) return;
    const key = `${abbr}:${file}`;
    if (cache.has(key)) {
      setData(cache.get(key));
      setLoading(false);
      return;
    }

    setLoading(true);
    setError(null);

    // Dynamic import — Vite resolves these at build time
    import(`../data/states/${abbr.toLowerCase()}/${file}.json`)
      .then((mod) => {
        const value = mod.default ?? mod;
        cache.set(key, value);
        setData(value);
        setLoading(false);
      })
      .catch((err) => {
        setError(err);
        setLoading(false);
      });
  }, [abbr, file]);

  return { data, error, loading };
}
