// StateOutline — renders the SVG outline of a state in a single accent color.
// Paths are pre-generated by scripts/generate-outlines.mjs from us-atlas.
//
// For Phase 1 (GA pilot) we have GA only. Phase 2 fills in the rest.

import outlines from './stateOutlines.js';

export default function StateOutline({ code, size = 120, color = 'var(--accent)', strokeWidth = 1.5 }) {
  const data = outlines[code];

  if (!data) {
    return (
      <div
        style={{
          width: size,
          height: size,
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          border: '1px dashed var(--rule)',
          color: 'var(--ink-soft)',
          fontFamily: 'Georgia, serif',
          fontSize: size * 0.4,
        }}
      >
        {code}
      </div>
    );
  }

  return (
    <svg
      viewBox={data.viewBox}
      width={size}
      height={size}
      style={{ display: 'inline-block' }}
      preserveAspectRatio="xMidYMid meet"
    >
      <path
        d={data.path}
        fill="none"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinejoin="round"
      />
      {data.capital && (
        <circle cx={data.capital.x} cy={data.capital.y} r={2.5} fill={color} />
      )}
    </svg>
  );
}
