// State outline SVG path data.
// Generated by scripts/generate-outlines.mjs from us-atlas TopoJSON.
//
// Phase 1: GA only (hand-traced for the pilot).
// Phase 2: run `npm run generate-outlines` to fill in all 50 states.
//
// Format: { viewBox: "x y w h", path: "M...Z", capital: { x, y } }

const outlines = {
  // Hand-traced GA outline. Will be replaced by us-atlas generated path in Phase 2.
  GA: {
    viewBox: '0 0 100 110',
    path: 'M 20 8 L 78 6 L 80 14 L 76 22 L 80 28 L 78 36 L 82 46 L 80 58 L 78 66 L 72 78 L 68 88 L 60 96 L 52 100 L 42 102 L 34 98 L 28 92 L 22 84 L 18 72 L 16 60 L 18 48 L 20 36 L 18 24 L 16 14 Z',
    capital: { x: 38, y: 38 }, // approx Atlanta position
  },
};

export default outlines;
